# Generated by Django 5.2 on 2025-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StackItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("date", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("github_url", models.URLField()),
                (
                    "stack",
                    models.ManyToManyField(
                        related_name="projects", to="portfolio.stackitem"
                    ),
                ),
            ],
        ),
    ]
