# Generated by Django 5.2 on 2025-04-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummarySection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(default="")),
                ("order", models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.AddField(
            model_name="project",
            name="long_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(default=""),
        ),
    ]
