# Generated by Django 5.2 on 2025-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_summarysection_remove_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
