# Generated by Django 5.2 on 2025-04-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_github_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="date",
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.CharField(default="Present", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
