# Generated by Django 5.2 on 2025-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_project_date_project_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default=models.AutoField(primary_key=True, serialize=False), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="long_description",
            field=models.TextField(default="No description yet"),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(default="No description yet"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
