# Generated by Django 5.2 on 2025-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_order_summarysection_display_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="long_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="short_description",
        ),
        migrations.AddField(
            model_name="project",
            name="header",
            field=models.TextField(default="No header yet"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
