# Generated by Django 5.2 on 2025-04-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_project_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stackitem",
            name="icon",
            field=models.CharField(default="", max_length=20),
        ),
    ]
