# Generated by Django 5.2 on 2025-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_stackitem_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stackitem",
            name="icon",
            field=models.CharField(default="", max_length=30),
        ),
    ]
