# Generated by Django 5.2 on 2025-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_stackitem_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(
                        default=models.AutoField(primary_key=True, serialize=False),
                        unique=True,
                    ),
                ),
                ("icon", models.CharField(default="", max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("header", models.TextField(default="No header yet")),
                ("description", models.TextField(default="No description yet")),
                (
                    "stack",
                    models.ManyToManyField(
                        related_name="experiences", to="portfolio.stackitem"
                    ),
                ),
            ],
        ),
    ]
