# Generated by Django 5.2 on 2025-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company",
            field=models.CharField(default="", max_length=50),
        ),
    ]
